/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package farmasalud.view;

import com.google.gson.JsonObject;
import dao.AdminDAO;
import dao.usuarioDAO;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;
import model.Medico;

/**
 *
 * @author Maria liz
 */
public class DialogCambiarContraseña extends javax.swing.JDialog {
    private JsonObject adminOriginal;// El usuario logueado
    private Medico medico;
    /**
     * Creates new form DialogCambiarContraseña
     */
    public DialogCambiarContraseña(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        txtContraseña.setEchoChar('•');
    }
    public DialogCambiarContraseña(java.awt.Frame parent, boolean modal, Medico medicoLogueado){
        super(parent, modal);
        initComponents();
        this.medico = medicoLogueado;
        cargarDatosDoctor();
    }
    public void setUsuario(JsonObject admin) {
        this.adminOriginal = admin;
    }
    
    private void cargarDatosDoctor() {
    if (usuarioDAO.medicoActual != null) {
        txtCorreoElectronico.setText(usuarioDAO.medicoActual.getEmail());
        txtContraseña.setText(usuarioDAO.medicoActual.getContraseña());
    } else {
        JOptionPane.showMessageDialog(this,
            "No se encontró información del doctor logueado.",
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}

   /* private void guardarEmailYContrasena() {
        String nuevoEmail = txtCorreoElectronico.getText().trim();
        String nuevaContrasena = txtContraseña.getText().trim();

        if (nuevoEmail.isEmpty() || nuevaContrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email y contraseña no pueden estar vacíos.");
            return;
        }

        if (adminOriginal == null) {
            JOptionPane.showMessageDialog(this, "No se ha establecido el usuario.");
            return;
        }

        String emailActual = adminOriginal.get("email").getAsString();

        boolean actualizado = new AdminDAO().actualizarEmailYContraseña(
                emailActual, nuevoEmail, nuevaContrasena
        );

        if (actualizado) {
            JOptionPane.showMessageDialog(this, "Email y contraseña actualizados correctamente.");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar. Verifica que el nuevo email no esté en uso.");
        }
    }
    public boolean actualizarEmailYContraseña(String emailOriginal, String nuevoEmail, String nuevaContrasena) {
    List<JsonObject> lista = cargarAdmins();
    boolean actualizado = false;

    for (JsonObject admin : lista) {
        if (admin.get("email").getAsString().equalsIgnoreCase(emailOriginal)) {
            admin.addProperty("email", nuevoEmail);
            admin.addProperty("contrasena", nuevaContrasena);
            actualizado = true;
            break;
        }
    }

    if (actualizado) {
        guardarAdmins(lista);
    }

    return actualizado;
}
*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCorreoElectronico = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BbtnGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorreoElectronico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoElectronicoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 124, 300, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("MIS CREDENCIALES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 220, 39));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 207, 109, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BbtnGuardar.setText("Guardar cambios\n");
        BbtnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbtnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(BbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 180, 300));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Correo :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 89, 39));

        txtContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 300, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("mostrar contraseña");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoElectronicoActionPerformed

    private void BbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbtnGuardarActionPerformed
     try {
        String nuevoCorreo = txtCorreoElectronico.getText().trim();
        String nuevaContraseña = txtContraseña.getText().trim();

        if (nuevoCorreo.isEmpty() || nuevaContraseña.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Debe completar ambos campos.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        dao.MedicoDAO medicoDAO = DAOImpl.MedicoDAOImpl.getInstancia();
        boolean actualizado = medicoDAO.actualizarCredenciales(
            usuarioDAO.medicoActual.getNumeroDocumento(),
            nuevoCorreo,
            nuevaContraseña
        );

        if (actualizado) {
            JOptionPane.showMessageDialog(this,
                "Datos actualizados correctamente.",
                "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // 🔥 MUY IMPORTANTE — actualizar los datos en memoria
            usuarioDAO.medicoActual.setEmail(nuevoCorreo);
            usuarioDAO.medicoActual.setContraseña(nuevaContraseña);

            dispose(); 
        } else {
            JOptionPane.showMessageDialog(this,
                "No se pudieron actualizar los datos. El correo ya está en uso.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error al actualizar: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    
    }    }//GEN-LAST:event_BbtnGuardarActionPerformed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
    txtContraseña.setEchoChar((char) 0);    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
        txtContraseña.setEchoChar('•');
    }//GEN-LAST:event_jLabel4MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogCambiarContraseña dialog = new DialogCambiarContraseña(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BbtnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreoElectronico;
    // End of variables declaration//GEN-END:variables
}
